version: "3.8"
services:
  front:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8888:80"
    networks:
      - tlc-network
networks:
  tlc-network:
    external: true